#! more info here: https://github.com/actions/labeler
documentation:
- any:
  - changed-files:
    - any-glob-to-any-file: ['**/*.md']

terraform:
- any:
  - changed-files:
    - any-glob-to-any-file: ['**/*.tf']

k8s:
- any:
  - changed-files:
    - any-glob-to-any-file: ['k8s/**/*', 'modules/**/k8s/**/*']

workflows:
- any:
  - changed-files:
    - any-glob-to-any-file: ['.github/**/*', 'CODEOWNERS', '.*.*', 'atlantis.yaml']

prod:
- any:
  - changed-files:
    - any-glob-to-any-file: ['**/*_p_*/**/*.tf']

non-prod:
- any:
  - changed-files:
    - any-glob-to-any-file: ['**/*_d_*/**/*.tf', '**/*_np_*/**/*.tf']