#! more info here: https://github.com/github/issue-labeler
# doc: https://github.com/github/issue-labeler
name: Issue labeler
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  issue-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@v3.3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ${{ '.github/issue-labeler.yml' }}
          enable-versioned-regex: 0
          include-title: 1