name: MegaLinter - Javascript

on:
  schedule:
    - cron: "0 7 * * 1"
  pull_request:
    branches: [main]

jobs:
  megalinter-javascript:
    uses: nosportugal/github-workflows-ccoe/.github/workflows/megalinter-javascript.yml@main
    secrets: inherit