name: Pull request labeler
on:
  # workflow triggers
  pull_request_target:
  workflow_dispatch:

jobs:
  pr-labels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ${{ '.github/pr-labeler.yml' }}